### ISSUE TITLE
Find food API worth using

### ISSUE THREAD

**Issue by thedanielenrico** [danmorales209/project-dan#6]

**Comment by danmorales209** [comment]
Found two working APIs (search for broccoli recipes)
1. [food2Fork example](https://github.com/danmorales209/project-dan/blob/morales/example/food2fork.json)
2. [Edamam example](https://github.com/danmorales209/project-dan/blob/morales/example/edamam.json)

**Food2Fork**
- Simple, but the API only returns a link to the recipe / recipe ingredients
- 50 requests / day

**Edamam**
- API returns a wealth of information (10x more), including ingredients, calories, etc, but might be a bit heavy to save to firebase.
- 5,000 requests / month

test.html under the morales brach has a working example
